services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    image: postgres:14
    env_file:
      - ./backend/.env
    ports:
      - "5433:5432" # Host 5433 → Container 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
