services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    expose:
      - "8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    image: postgres:14
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt

volumes:
  pgdata:
